# Functions to create different plots

#' Calculate Survival Probabilities
#'
#' Calculates the probability of surviving to a certain age from an initial state and age
#'
#' @param init_state
#' 0 (for healthy) or 1 (for disabled)
#' @param init_age
#' numeric between 0 and closure_age denoting age of individual.
#' @param closure_age
#' maximum life span
#' @param target_age
#' numeric between 0 and closure_age denoting the target age to survive to.
#' @param trans_probs
#' list of transition probability matrices; this could be generated by \code{health3_get_trans_probs}.
#' @param end_state
#' default NULL to return probability of surviving. Set to 0 for probability ending is healthy, and 1 for disabled.
#' @param frequency
#' string selecting the simulation frequency: "year", "quarter", or "month". Default is "year".
#'
#' @return
#' numeric denoting probability of surviving to end age in end state
#'
#' @noRd
#'
health3_surv_prob <- function(init_state, init_age, closure_age, target_age, trans_probs, end_state = NULL, frequency = "year") {
    # screening for errors
    if (init_state != 0 & init_state != 1) {
        stop('invalid state, use 0 for healthy and 1 for disabled')
    }

    if (!is.null(end_state)) {
        if (end_state != 0 & end_state != 1) {
            stop('invalid end state, use 0 for healthy and 1 for disabled')
        }
    }

    if (init_age >= target_age) {
        stop('initial age is greater than or equal to target age')
    }

    if (init_age < 0 | init_age > closure_age) {
        stop('invalid initial age')
    }

    if (target_age < 0 | target_age > closure_age) {
        stop('invalid target age')
    }

    # Map the string frequency to numeric steps per year
    if (frequency == "year") {
        freq <- 1
    } else if (frequency == "quarter") {
        freq <- 4
    } else if (frequency == "month") {
        freq <- 12
    } else {
        stop("Frequency must be one of 'year', 'quarter', and 'month'.")
    }

    # Calculate number of transitions needed based on freq
    steps <- round((target_age - init_age) * freq)

    if (steps > length(trans_probs)) {
        stop('target age exceeds the time steps available in trans_probs')
    }

    # we multiply probability matrices in the trans_probs to get transition rates
    if (steps == 0) {
        P <- diag(3)
    } else {
        P <- Reduce('%*%', trans_probs[1:steps])
    }

    # return relevant item from the probability matrix
    if (is.null(end_state)) {
        return(P[init_state + 1,  1] + P[init_state + 1, 2])
    } else {
        return(P[init_state + 1, end_state + 1])
    }
}


#' Create Survival Probability Plots
#'
#' Create a plot of survival probabilities to alive, health, and disabled states.
#'
#' @param init_state
#' 0 for healthy, 1 for disabled.
#' @param init_age
#' numeric between 0 and closure_age denoting initial age of individual.
#' @param closure_age
#' maximum life span
#' @param trans_probs
#' list of transition probability matrices, this could be generated by \code{get_trans_probs}.
#' @param frequency
#' string selecting the simulation frequency: "year", "quarter", or "month". Default is "year".
#'
#' @return
#' line plot with 3 lines, each denoting survival probability, survival probability to
#' disabled, and survival probability to healthy.
#'
#' @import tidyr dplyr ggplot2
#'
#' @noRd
#'
health3_prob_plots <- function(init_age, closure_age, init_state, trans_probs, frequency = "year") {

    # flagging errors
    if (init_age < 0 | init_age > closure_age) {
        stop('invalid age')
    }

    if (init_state != 0 & init_state != 1) {
        stop('invalid state; enter 0 for healthy, 1 for disabled')
    }

    # Map the string frequency to numeric steps per year
    if (frequency == "year") {
        freq <- 1
    } else if (frequency == "quarter") {
        freq <- 4
    } else if (frequency == "month") {
        freq <- 12
    } else {
        stop("Frequency must be one of 'year', 'quarter', and 'month'.")
    }

    num_transitions <- length(trans_probs)

    # Pre-allocate a matrix to hold the state probabilities over time
    probs <- matrix(0, nrow = num_transitions + 1, ncol = 3)

    # Initialize the starting state vector
    probs[1, init_state + 1] <- 1

    # Fast vector-matrix multiplication to calculate the entire curve
    for (i in seq_len(num_transitions)) {
        probs[i+1, ] <- probs[i, ] %*% trans_probs[[i]]
    }

    # create fractional age axis based on freq
    ages <- init_age + (0:num_transitions) / freq

    # Extract probabilities
    healthy_probs <- probs[, 1]
    disabled_probs <- probs[, 2]
    alive_probs <- healthy_probs + disabled_probs

    # create dataframe for ggplot
    survival_df <- data.frame(
        'age' = ages,
        'alive' = alive_probs,
        'healthy' = healthy_probs,
        'disabled' = disabled_probs
    )

    updated_df <- survival_df %>%
        dplyr::select(age, alive, healthy, disabled) %>%
        tidyr::gather(key = 'Type', value = 'value', -age)

    updated_df$Type <- factor(updated_df$Type, levels = c('alive', 'healthy', 'disabled'))

    surv_plot <- ggplot2::ggplot(updated_df, ggplot2::aes(x = age, y = value)) +
        ggplot2::geom_line(ggplot2::aes(color = Type)) +
        ggplot2::scale_color_manual(labels = c('Alive', 'H', 'F'),
                                    values = c('darkolivegreen3', 'skyblue2', 'lightcoral')) +
        ggplot2::labs(x = "Ages", y = "") +
        ggplot2::theme_classic() +
        ggplot2::theme(legend.title = ggplot2::element_blank(),
                       legend.spacing.y = ggplot2::unit(0, "mm"),
                       panel.border = ggplot2::element_rect(colour = "black", fill=NA),
                       aspect.ratio = 1, axis.text = ggplot2::element_text(colour = 1, size = 12),
                       legend.background = ggplot2::element_blank(),
                       legend.box.background = ggplot2::element_rect(colour = "black"))

    return(surv_plot)
}
