#' Functions to create different plots
#'
#' Create a plot of survival probabilities to H, M, D, MD and Dead states.
#'
#' @param init_state
#' 0 for H state, 1 for M state, 2 for D state, 3 for MD state
#' @param init_age
#' integer between 0 and closure age (inclusive) denoting initial age of individual. This has
#' to be the same as the initial age used for transition probability matrices simulation.
#' @param closure_age
#' maximum life span
#' @param trans_probs
#' list of transition probability matrices, this could be generated by \code{get_trans_probs}.
#'
#' @return
#' line plot with 5 lines, each denoting probabilities of being in the
#' states H, M, D, MD, Dead respectively.
#'
#' @import tidyr dplyr ggplot2
#'
#' @noRd
#'
#' @examples example
health5_prob_plots <- function(init_age, closure_age, init_state, trans_probs) {
    age <- H <- M <- D <- MD <- Dead <- value <- Type <- NULL
  # flagging errors
  if (init_age < 0 | init_age > closure_age) {
    stop('invalid age')
  }

  if (as.integer(init_age) != init_age) {
    stop('initial age must be an integer')
  }

  if (init_state != 0 & init_state != 1 & init_state != 2 & init_state != 3) {
    stop('invalid state; enter 0 for H, 1 for M, 2 for D, 3 for MD')
  }

lifetable=create_life_table(trans_probs, init_age, closure_age, init_state, cohort = 1)

  # create age axis
  ages <- init_age:closure_age

  # create dataframe for ggplot
  survival_df <- data.frame('age' = ages,
                            'Alive'=lifetable[,'Alive'],
                            'H' = lifetable[,'H'],
                            'M' = lifetable[,'M'],
                            'D' = lifetable[,'D'],
                            'MD'= lifetable[,'MD']
                              )

  updated_df <- survival_df %>%
    dplyr::select(age, Alive, H, M, D, MD) %>%
    tidyr::gather(key = 'Type', value = 'value', -age)
  updated_df$Type <- factor(updated_df$Type, levels = c('Alive', 'H', 'M', 'D', 'MD'))

  surv_plot <- ggplot2::ggplot(updated_df, aes(x = age, y = value)) +
      ggplot2::geom_line(aes(color = Type)) +
      ggplot2::scale_color_manual(labels = c('Alive', 'H', 'M', 'D', 'MD'),
                                  values = c('darkolivegreen3', 'skyblue2', 'blue', 'lightcoral', 'darkgoldenrod1')) +
      # ggplot2::ggtitle('Probability of Surviving to each Different State')+
      ggplot2::labs(x = "Ages", y = "")+ theme_classic() +
      theme(legend.title = element_blank(),
        legend.spacing.y = unit(0, "mm"),
        panel.border = element_rect(colour = "black", fill=NA),
        aspect.ratio = 1, axis.text = element_text(colour = 1, size = 12),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"))
  return(surv_plot)
}



