#' Functions to create different plots
#'
#' Create a plot of survival probabilities to H, M, D, MD and Dead states.
#'
#' @param init_state
#' 0 for H state, 1 for M state, 2 for D state, 3 for MD state
#' @param init_age
#' numeric between 0 and closure age denoting initial age of individual.
#' @param closure_age
#' maximum life span
#' @param trans_probs
#' list of transition probability matrices, this could be generated by \code{get_trans_probs}.
#' @param freq
#' integer denoting the number of transition steps per year
#'
#' @return
#' line plot with 5 lines, each denoting probabilities of being in the
#' states H, M, D, MD, Dead respectively.
#'
#' @import tidyr dplyr ggplot2
#'
#' @noRd
#'
health5_prob_plots <- function(init_age, closure_age, init_state, trans_probs, freq = 1) {

    # flagging errors
    if (init_age < 0 | init_age > closure_age) {
        stop('invalid age')
    }

    if (!init_state %in% c(0, 1, 2, 3)) {
        stop('invalid state; enter 0 for H, 1 for M, 2 for D, 3 for MD')
    }

    # Generate the expected state probabilities using the highly optimized lifetable function
    lifetable <- create_life_table(trans_probs, init_age, closure_age, init_state, cohort = 1)

    # Create dataframe for ggplot directly using the exact Age column from lifetable
    # (which inherently scales to sub-annual frequencies)
    survival_df <- data.frame(
        'age' = lifetable[, 'Age'],
        'Alive' = lifetable[, 'Alive'],
        'H' = lifetable[, 'H'],
        'M' = lifetable[, 'M'],
        'D' = lifetable[, 'D'],
        'MD' = lifetable[, 'MD']
    )

    updated_df <- survival_df %>%
        dplyr::select(age, Alive, H, M, D, MD) %>%
        tidyr::gather(key = 'Type', value = 'value', -age)

    updated_df$Type <- factor(updated_df$Type, levels = c('Alive', 'H', 'M', 'D', 'MD'))

    surv_plot <- ggplot2::ggplot(updated_df, ggplot2::aes(x = age, y = value)) +
        ggplot2::geom_line(ggplot2::aes(color = Type)) +
        ggplot2::scale_color_manual(labels = c('Alive', 'H', 'M', 'D', 'MD'),
                                    values = c('darkolivegreen3', 'skyblue2', 'blue', 'lightcoral', 'darkgoldenrod1')) +
        ggplot2::labs(x = "Ages", y = "") +
        ggplot2::theme_classic() +
        ggplot2::theme(legend.title = ggplot2::element_blank(),
                       legend.spacing.y = ggplot2::unit(0, "mm"),
                       panel.border = ggplot2::element_rect(colour = "black", fill=NA),
                       aspect.ratio = 1, axis.text = ggplot2::element_text(colour = 1, size = 12),
                       legend.background = ggplot2::element_blank(),
                       legend.box.background = ggplot2::element_rect(colour = "black"))

    return(surv_plot)
}
